project:
  type: website

website:
  title: "Anh Phan's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AnhHoangNamPhan
format:
  html:
    theme: minty
    css: styles.css



